{% set name = "quart-cors" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/quart_cors-{{ version }}.tar.gz
  sha256: e7c3f176624cfaa934ea96eddbcaea0b6c225d8eee543f97bce3bdc22e1e00ef

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - poetry_core >=1.0.0
    - pip
  run:
    - python >=3.7
    - quart >=0.15
    - typing_extensions python<3.10

test:
  imports:
    - quart_cors
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pgjones/quart-cors/
  summary: A Quart extension to provide Cross Origin Resource Sharing, access control, support
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
    - maxyme
